// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-powered pricing suggestions for farmers based on current demand, seasonality, and regional factors.
 *
 * - getPricingGuidance - A function that generates pricing guidance for a specific produce.
 * - PricingGuidanceInput - The input type for the getPricingGuidance function.
 * - PricingGuidanceOutput - The return type for the getPricingGuidance function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PricingGuidanceInputSchema = z.object({
  produceType: z.string().describe('The type of produce (e.g., tomatoes, corn, apples).'),
  quantity: z.number().describe('The quantity of produce available (e.g., 100 kg).'),
  quality: z.string().describe('The quality of the produce (e.g., premium, standard, fair).'),
  location: z.string().describe('The regional location where the produce is being sold (e.g., Kisumu, Nairobi).'),
});
export type PricingGuidanceInput = z.infer<typeof PricingGuidanceInputSchema>;

const PricingGuidanceOutputSchema = z.object({
  suggestedPrice: z.number().describe('The AI-suggested price per unit (e.g., per kg) in KES.'),
  reasoning: z.string().describe('The AI reasoning behind the suggested price, considering demand, seasonality, and regional factors.'),
});
export type PricingGuidanceOutput = z.infer<typeof PricingGuidanceOutputSchema>;

export async function getPricingGuidance(input: PricingGuidanceInput): Promise<PricingGuidanceOutput> {
  return pricingGuidanceFlow(input);
}

const pricingGuidancePrompt = ai.definePrompt({
  name: 'pricingGuidancePrompt',
  input: {schema: PricingGuidanceInputSchema},
  output: {schema: PricingGuidanceOutputSchema},
  prompt: `You are an AI assistant that provides pricing guidance to farmers based on current market conditions.

  Consider the following factors when determining the optimal price:
  - Current demand for the produce in the specified region.
  - Seasonality and its impact on availability.
  - Regional market prices for similar produce.

  Based on these factors, suggest a price per unit (KES) for the following produce:
  Produce Type: {{{produceType}}}
  Quantity: {{{quantity}}} kg
  Quality: {{{quality}}}
  Location: {{{location}}}

  Provide a brief reasoning for your suggested price.
  `,
});

const pricingGuidanceFlow = ai.defineFlow(
  {
    name: 'pricingGuidanceFlow',
    inputSchema: PricingGuidanceInputSchema,
    outputSchema: PricingGuidanceOutputSchema,
  },
  async input => {
    const {output} = await pricingGuidancePrompt(input);
    return output!;
  }
);
